name = "sw1ft"
main = "worker.js"
compatibility_date = "2025-01-01"

[assets]
binding = "ASSETS"
directory = "./dist"
not_found_handling = "single-page-application"

[[kv_namespaces]]
binding = "SW1FT_SESSIONS"
id = "REPLACE_WITH_KV_NAMESPACE_ID"
